package frc.team449.subsystems.drive.swerve

// TODO: Add constants generated by Tuner X Swerve Proj Generator.
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
object TunerConstants
